<a href="https://colab.research.google.com/github/Md-Thahir/AI-Tools-Lab/blob/main/Exp_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
'''a.To generate an array of random numbers from a normal distribution for the array of a
given shape.'''
import numpy as np
# Enter the value of n
n=int(input('Enter no. of values:'))
# Generates n random numbers from Normal Distribution
rand_num = np.random.normal(0,1,n)
print(n, " random numbers from a standard normal distribution:")
print(rand_num)
arr=np.array([rand_num])
# Displays the size of the Array
print(arr.shape)

Enter no. of values:10
10  random numbers from a standard normal distribution:
[-1.08957636 -1.59904117 -0.6413815   1.8456476  -0.887324   -0.05924803
  0.32828573  0.07647769  0.23659604 -0.87328141]
(1, 10)


In [3]:
'''b. Implement Arithmetic operations on two arrays (perform broadcasting also.)'''
#Generates an Array A with 0 to 11 in a 3X4 form
A = np.arange(12).reshape(3,4)
print(A)
#Generates an Array B with 0 to 3 in a 1X3 form
B = np.arange(4)
print(B)
#Performs the addition between A and B
c=A+B
print(c)
#Similarly perform remaining arithmetic operations (Subtraction,multiplication, division )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [4]:
'''c. Find minimum, maximum, mean in a given array. ( in both the axes )'''
arr = np.array([[11, 2, 3],[4, 5, 16],[7, 81, 22]])
# finding the maximum and minimum element in the array
max_element = np.max(arr)
min_element = np.min(arr)
# printing the result
print('maximum element in the array is:', max_element)
print('minimumm element in the array is:', min_element)
# finding the maximum and
# minimum element in the array
max_element_column = np.max(arr, 0)
max_element_row = np.max(arr, 1)
min_element_column = np.amin(arr, 0)
min_element_row = np.amin(arr, 1)
# printing the result
print('maximum elements in the columns of the array is:',max_element_column)
print('maximum elements in the rows of the array is:', max_element_row)
print('minimum elements in the columns of the array is:',min_element_column)
print('minimum elements in the rows of the array is:',min_element_row)
# mean of the flattened array
print("\nmean of arr, axis = None : ", np.mean(arr))
# mean along the axis = 0 (row-wise)
print("\nmean of arr, axis = 0 : ", np.mean(arr, axis = 0))
# mean along the axis = 1 (Column-wise)
print("\nmean of arr, axis = 1 : ", np.mean(arr, axis = 1))

maximum element in the array is: 81
minimumm element in the array is: 2
maximum elements in the columns of the array is: [11 81 22]
maximum elements in the rows of the array is: [11 16 81]
minimum elements in the columns of the array is: [4 2 3]
minimum elements in the rows of the array is: [2 4 7]

mean of arr, axis = None :  16.77777777777778

mean of arr, axis = 0 :  [ 7.33333333 29.33333333 13.66666667]

mean of arr, axis = 1 :  [ 5.33333333  8.33333333 36.66666667]


In [5]:
'''d. Implement np.arange and np.linspace functions.'''

# Prints all numbers from 0 to 9 in steps of 1
arr=np.linspace(start = 0, stop = 10, num = 11,dtype = int)
print(arr)
arr=np.linspace(start = 0, stop = 1, num = 11)
print(arr)
# Prints all numbers from 1 to 2 in steps of 0.1
print(np.arange(1, 2, 0.1))

[ 0  1  2  3  4  5  6  7  8  9 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [6]:
'''e. Create a pandas series from a given list.'''

# import pandas lib. as pd
import pandas as pd
# Assume l1 is a list of the following words
l1 = ['ZERO', 'ONE', 'TWO', 'THREE','FOUR', 'FIVE', 'SIX','SEVEN','EIGHT','NINE','TEN']
# create Pandas Series with define indexes
x = pd.Series(l1)
# print the Series
print(x)

0      ZERO
1       ONE
2       TWO
3     THREE
4      FOUR
5      FIVE
6       SIX
7     SEVEN
8     EIGHT
9      NINE
10      TEN
dtype: object


In [7]:
'''f. Create pandas series with data and index and display the index values.'''

# import pandas lib. as pd
import pandas as pd
# create Pandas Series with define indexes
x = pd.Series([10, 20, 30, 40, 50], index =['a', 'b', 'c', 'd', 'e'])
# print the Series
print(x)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [8]:
'''g. Create a data frame with columns at least 5 observations
i. select a particular column from the DataFrame
ii. Summarize the data frame and observe the stats of the DataFrame created
iii. Observe the mean and standard deviation of the data frame and print the values.'''

import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily'],'score': [12.5, 9, 16.5,np.nan, 9],'attempts': [1, 3, 2, 3, 2],'qualify': ['yes', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e']
df = pd.DataFrame(exam_data , index=labels)
print("Dataset is as follows")
print(df)
print("Summary of the Dataset")
print(df.info())
print("Statistical values of numerical attributes")
print(df.describe())
meanvalue=df.score.mean()
stdvalue=df.score.std()
print('mean value of Score is',meanvalue)
print('Standard deviation of score is',stdvalue)

Dataset is as follows
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
Summary of the Dataset
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      5 non-null      object 
 1   score     4 non-null      float64
 2   attempts  5 non-null      int64  
 3   qualify   5 non-null      object 
dtypes: float64(1), int64(1), object(2)
memory usage: 200.0+ bytes
None
Statistical values of numerical attributes
           score  attempts
count   4.000000   5.00000
mean   11.750000   2.20000
std     3.570714   0.83666
min     9.000000   1.00000
25%     9.000000   2.00000
50%    10.750000   2.00000
75%    13.500000   3.00000
max    16.500000   3.00000
mean value of Score is 11.75
Standard de