<a href="https://colab.research.google.com/github/Md-Thahir/AI-Tools-Lab/blob/main/exp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

def mat_add(mat1,mat2):
  return np.add(mat1,mat2)

def mat_sub(mat1,mat2):
  return np.subtract(mat1,mat2)

def mat_mul(mat1,mat2):
  return np.dot(mat1,mat2)

def mat_inv(mat):
  return np.linalg.inv(mat)

def mat_transpose(mat):
  return np.transpose(mat)

def print_mat(mat):
  print(mat)

mat1=np.array([[1,2],[3,4]])
mat2=np.array([[6,7],[8,9]])

print("Matrix Addition")
print_mat(mat_add(mat1,mat2))

print("\n Matrix Subtraction")
print_mat(mat_sub(mat1,mat2))

print("\n Matrix Multiplication")
print_mat(mat_mul(mat1,mat2))

print("\n Matrix Inverse")
print_mat(mat_inv(mat1))
print("\n")
print_mat(mat_inv(mat2))

print("\n Matrix Transpose")
print_mat(mat_transpose(mat1))
print("\n")
print_mat(mat_transpose(mat2))

Matrix Addition
[[ 7  9]
 [11 13]]

 Matrix Subtraction
[[-5 -5]
 [-5 -5]]

 Matrix Multiplication
[[22 25]
 [50 57]]

 Matrix Inverse
[[-2.   1. ]
 [ 1.5 -0.5]]


[[-4.5  3.5]
 [ 4.  -3. ]]

 Matrix Transpose
[[1 3]
 [2 4]]


[[6 8]
 [7 9]]
